name: Build Zygisk Dump Dex

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install Rust targets
        run: |
          rustup target install aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android

      - name: Install Just
        run: cargo install just

      - name: Install cargo-ndk
        run: cargo install cargo-ndk --force

      - name: Build project for all targets
        run: |
          cargo ndk --target armeabi-v7a build --release
          cargo ndk --target arm64-v8a build --release
          cargo ndk --target x86 build --release
          cargo ndk --target x86_64 build --release
          just package-release

      - name: Upload built artifact
        uses: actions/upload-artifact@v4
        with:
          name: zygisk-debug-zip
          path: out/zygisk-*.zip
          compression-level: 9